version: "3.9"
services:
  db:
    image: postgres:16.9-bullseye
    container_name: tp-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data_tp:/var/lib/postgresql/data
volumes:
  db_data_tp: